#!/usr/local/bin/python

from ftplib import FTP
from ftplib import error_temp
from ftplib import error_perm
from getpass import getpass
host = ''
user = ''
password = ''
file = None

def writeFileLineByLine(line):
	file.write(line)
	file.write('\n')

def writeBinary(data):
	file.write(data)

def getUserInput(msg):
	inputString = ''
	try:
		inputString = eval("raw_input('" + msg + "')")
	except (SyntaxError, NameError):
		inputString = eval("input('" + msg + "')")
	return inputString

ftp = FTP()
msg = ''
connected = False
while not connected:
	# host = getUserInput('Host name (URL): ').strip()
	host = getUserInput('Host name (URL): ').strip()
	try:
		msg = ftp.connect(host)
	except error_temp as e:
		print(e)
	except error_perm as e:
		print(e)
	else:
		connected = True
		print(msg)
loggedIn = False
while not loggedIn:
	user = getUserInput('Username (blank for anonymous): ').strip()
	password = getpass('Password (blank for anonymous): ').strip()
	try:
		msg = ftp.login(user, password)
	except error_temp as e:
		print(e)
	except error_perm as e:
		print(e)
	else:
		loggedIn = True
		print(msg)
cmd = getUserInput('Command: ').strip()
while cmd != 'quit':
	# print ("You typed", cmd)
	cmdList = cmd.split()
	# print(str(cmdList))
	if cmdList[0] == 'ls':
		print(ftp.dir())
	elif cmdList[0] == 'cd':
		try:
			msg = ftp.cwd(cmdList[1])
		except error_perm as e:
			print(e)
		else:
			print(msg)
	elif cmdList[0] == 'get':
		try:
			file = open(cmdList[1], 'wb')
			ftp.retrbinary(('RETR ' + cmdList[1]), writeBinary)
			file.close()
		except IOError as e:
			print('IOError: ' + str(e))
		except error_perm as e:
			print(e)
		else:
			print('Got ' + cmdList[1])
	elif cmdList[0] == 'put':
		try:
			file = open(cmdList[1], 'rb')
			ftp.storbinary('STOR ' + cmdList[1], file)
			file.close()
		except IOError as e:
			print('IOError: ' + str(e))
		except error_perm as e:
			print(e)
		else:
			print('Put ' + cmdList[1])
	elif cmdList[0] == 'mkdir':
		try:
			print(ftp.mkd(cmdList[1]))
		except error_perm as e:
			print(e)
		else:
			print('Made new directory: ' + cmdList[1])
	elif cmdList[0] == 'rmdir':
		try:
			print(ftp.rmd(cmdList[1]))
		except error_perm as e:
			print(e)
		else:
			print('Removed directory: ' + cmdList[1])
	elif cmdList[0] == 'pwd':
		try:
			print(ftp.pwd())
		except error_perm as e:
			print(e)
	elif cmdList[0] == 'mv':
		try:
			print(ftp.rename(cmdList[1], cmdList[2]))
		except error_perm as e:
			print(e)
		else:
			print('Moved ' + cmdList[1] + ' to ' + cmdList[2])
	elif cmdList[0] == 'rm':
		try:
			print(ftp.delete(cmdList[1]))
		except error_perm as e:
			print(e)
		else:
			print('Deleted ' + cmdList[1])
	cmd = getUserInput('Command: ').strip()

try:
	print(ftp.quit())
except:
	print(ftp.close())
